//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS_DAL.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BMSModelContainer : DbContext
    {
        public BMSModelContainer()
            : base("name=BMSModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TUser> TUsers { get; set; }
        public DbSet<TFixture> TFixtures { get; set; }
        public DbSet<TVessel> TVessels { get; set; }
        public DbSet<TInvoice> TInvoices { get; set; }
        public DbSet<TInvoiceDetail> TInvoiceDetails { get; set; }
        public DbSet<TClient> TClients { get; set; }
        public DbSet<TMenu> TMenus { get; set; }
        public DbSet<TLog> TLogs { get; set; }
    }
}
