//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMS_DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TInvoice
    {
        public int ID { get; set; }
        public string FIXNO { get; set; }
        public string REFNO { get; set; }
        public string INVOICE_DATE { get; set; }
        public string MESSES { get; set; }
        public int VSL_ID { get; set; }
        public System.DateTimeOffset CP_DATE { get; set; }
        public string CP_TYPE { get; set; }
        public string CP_DESC { get; set; }
        public decimal HRORFRT { get; set; }
        public decimal DAYSORMT { get; set; }
        public string ATIN { get; set; }
        public string CWNO { get; set; }
        public string OWR { get; set; }
        public decimal BRKRATE_OWR { get; set; }
        public decimal BRKAMOUNT_OWR { get; set; }
        public string CHR { get; set; }
        public decimal BRKRATE_CHR { get; set; }
        public decimal BRKAMOUNT_CHR { get; set; }
        public string PERIODS { get; set; }
        public string BANKACCOUNT { get; set; }
        public decimal RECEIVABLEAMOUNT { get; set; }
        public string STATUS { get; set; }
        public string REMARK { get; set; }
        public string OPER { get; set; }
        public decimal OP_DT { get; set; }
        public System.DateTimeOffset RECEIVABLEDATE { get; set; }
    }
}
